pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// Colors come from pywal (~/.cache/wal/colors.json) and update live whenever
// `wal` runs. Dark like zenities by default; set `mode` to "auto" to let the
// wallpaper's brightness pick a dark or light variant.
// Helpers mirror the SCSS functions used by zenities' eww config.
Singleton {
    id: root

    // "dark" (zenities default), "light", or "auto" (follow the wallpaper)
    readonly property string mode: "dark"
    // In auto mode, wallpapers brighter than this (mean luminance 0..1) get the light theme
    readonly property real lightThreshold: 0.6

    property string wallpaper: ""
    property real wallpaperLuma: 0
    readonly property bool light: mode === "light" || mode === "auto" && wallpaperLuma > lightThreshold

    property var raw: null

    readonly property color background: light ? toneHsl(rawBg, 0.2, 0.92, 0.92) : toneHsl(rawBg, 0.15, 0, 0.04)
    readonly property color foreground: light ? toneHsl(rawBg, 0.15, 0.13, 0.13) : rawFg
    readonly property color color0: background
    readonly property color color1: accent(1)
    readonly property color color2: accent(2)
    readonly property color color3: accent(3)
    readonly property color color4: accent(4)
    readonly property color color5: accent(5)
    readonly property color color6: accent(6)
    readonly property color color7: accent(7)
    readonly property color color8: accent(8)
    readonly property color color9: accent(9)
    readonly property color color10: accent(10)
    readonly property color color11: accent(11)
    readonly property color color12: accent(12)
    readonly property color color13: accent(13)
    readonly property color color14: accent(14)
    readonly property color color15: foreground

    readonly property color rawBg: raw ? raw.special.background : "#0a090a"
    readonly property color rawFg: raw ? raw.special.foreground : "#e6dcd5"

    readonly property string font: "Iosevka"
    readonly property string iconFont: "Iosevka Nerd Font"
    readonly property real rem: 15

    // SCSS mix($a, $b, $weight): weight of $a
    function mix(a, b, w) {
        return Qt.rgba(a.r * w + b.r * (1 - w), a.g * w + b.g * (1 - w), a.b * w + b.b * (1 - w), 1);
    }

    // SCSS lighten($c, $amount)
    function lighten(c, amount) {
        return Qt.hsla(Math.max(0, c.hslHue), c.hslSaturation, Math.min(1, c.hslLightness + amount), 1);
    }

    function alpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a);
    }

    // Keep hue, cap saturation, clamp lightness into [minL, maxL]
    function toneHsl(c, maxS, minL, maxL) {
        return Qt.hsla(Math.max(0, c.hslHue), Math.min(c.hslSaturation, maxS), Math.max(minL, Math.min(maxL, c.hslLightness)), 1);
    }

    // Accents keep pywal's hue but are pushed to readable contrast against
    // the background (zenities generates with wallust check_contrast=true).
    function accent(i) {
        const fallback = ["#0a090a", "#a87a63", "#4a8c96", "#3f7a84", "#5f8f8f", "#6b9ea3", "#8fb3b0", "#e6dcd5", "#6b6563", "#a87a63", "#62b3be", "#54a3b0", "#7fbfbf", "#8fd3d9", "#bfefeb"];
        const c = Qt.color(raw ? raw.colors["color" + i] : fallback[i]);
        const l = light ? Math.min(c.hslLightness, 0.4) : Math.max(c.hslLightness, 0.5);
        return Qt.hsla(Math.max(0, c.hslHue), c.hslSaturation, l, 1);
    }

    FileView {
        path: Quickshell.env("HOME") + "/.cache/wal/colors.json"
        watchChanges: true
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            try {
                const j = JSON.parse(text());
                root.raw = j;
                if (j.wallpaper !== root.wallpaper) {
                    root.wallpaper = j.wallpaper;
                    luma.running = true;
                }
            } catch (e) {}
        }
    }

    // ---- Sync mango's colors (~/.config/mango/colors.conf, sourced by its config) ----
    function hex(c) {
        const h = v => Math.round(v * 255).toString(16).padStart(2, "0");
        return "0x" + h(c.r) + h(c.g) + h(c.b) + "ff";
    }

    readonly property string mangoColors: ["# generated by quickshell from pywal — do not edit", "rootcolor=" + hex(background), "bordercolor=" + hex(mix(background, foreground, 0.8)), "focuscolor=" + hex(color2), "maximizescreencolor=" + hex(color4), "urgentcolor=" + hex(color1), "scratchpadcolor=" + hex(color5), "globalcolor=" + hex(color6), "overlaycolor=" + hex(color3), "shadowscolor=0x000000ff", ""].join("\n")

    onMangoColorsChanged: if (raw)
        mangoSync.restart()

    Timer {
        id: mangoSync
        interval: 800
        onTriggered: mangoWrite.running = true
    }

    Process {
        id: mangoWrite
        command: ["sh", "-c", "f=\"$HOME/.config/mango/colors.conf\"; [ \"$(cat \"$f\" 2>/dev/null)\" = \"$1\" ] && exit 0; printf '%s' \"$1\" > \"$f\" && mmsg dispatch reload_config >/dev/null", "sh", root.mangoColors.trim()]
    }

    // ---- Sync kitty (zenities-colors.conf) and GTK's light/dark preference ----
    function h6(c) {
        const h = v => Math.round(v * 255).toString(16).padStart(2, "0");
        return "#" + h(c.r) + h(c.g) + h(c.b);
    }

    readonly property string kittyColors: {
        // In light mode ANSI black/white swap roles so terminal text stays readable
        const black = light ? foreground : background;
        const white = light ? mix(foreground, background, 0.65) : foreground;
        const lines = ["# generated by quickshell (zenities theme) — do not edit", "background " + h6(background), "foreground " + h6(foreground), "cursor " + h6(foreground), "cursor_text_color " + h6(background), "selection_background " + h6(color2), "selection_foreground " + h6(background), "url_color " + h6(color4), "active_border_color " + h6(color2), "inactive_border_color " + h6(mix(background, foreground, 0.8)), "color0 " + h6(black), "color8 " + h6(mix(foreground, background, 0.5)), "color7 " + h6(white), "color15 " + h6(light ? mix(foreground, background, 0.8) : lighten(foreground, 0.1))];
        for (let i = 1; i <= 6; i++) {
            lines.push("color" + i + " " + h6(root["color" + i]));
            lines.push("color" + (i + 8) + " " + h6(light ? Qt.darker(root["color" + i], 1.15) : lighten(root["color" + i], 0.08)));
        }
        return lines.join("\n");
    }

    onKittyColorsChanged: if (raw)
        appSync.restart()
    onLightChanged: if (raw)
        appSync.restart()

    Timer {
        id: appSync
        interval: 800
        onTriggered: appWrite.running = true
    }

    Process {
        id: appWrite
        command: ["sh", "-c", "f=\"$HOME/.config/kitty/zenities-colors.conf\"; printf '%s\\n' \"$1\" > \"$f\"; " + "for s in /tmp/kitty-*; do [ -S \"$s\" ] && kitty @ --to \"unix:$s\" set-colors -a -c \"$f\" >/dev/null 2>&1; done; " + "command -v gsettings >/dev/null && gsettings set org.gnome.desktop.interface color-scheme \"$2\"", "sh", root.kittyColors, root.light ? "prefer-light" : "prefer-dark"]
    }

    Process {
        id: luma
        command: ["magick", root.wallpaper + "[0]", "-resize", "64x64!", "-colorspace", "Gray", "-format", "%[fx:mean]", "info:"]
        stdout: StdioCollector {
            onStreamFinished: {
                const v = parseFloat(text);
                if (!isNaN(v))
                    root.wallpaperLuma = v;
            }
        }
    }
}
