# include ~/.cache/wal/colors-kitty.conf
# zenities look — colors follow pywal + wallpaper light/dark (written by quickshell)
include zenities-colors.conf
background_opacity 1

# Window settings
confirm_os_window_close 0

# Cursor settings
cursor_shape beam
cursor_trail 1

# Shell and other settings
shell /usr/bin/zsh
enable_graphics yes

editor neovim
allow_hyperlinks yes
allow_remote_control yes
enabled_layouts all
enable_audio_bell no

# Window settings
confirm_os_window_close 0

# Cursor settings
cursor_shape beam
cursor_trail 1

# Shell and other settings
shell /usr/bin/zsh
enable_graphics yes
# window_padding_width 5 5

# zenities
font_family Iosevka
window_margin_width 18
listen_on unix:/tmp/kitty
